parameters:
  azureSubscription: ''
  aksConnection: ''
  acrName: ''
  chartName: ''
  deployment: ''
  deploymentDisplayName: ''
  releaseName: ''
  pool: ''
  env: ''
  namespace: 'default'
  helmOverrideValues: ''

jobs:
- deployment: ${{ parameters.deployment }}
  displayName: ${{ parameters.deploymentDisplayName }}
  pool:
    vmImage: ${{ parameters.pool }}
  environment: ${{ parameters.env }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: HelmInstaller@1
          displayName: Helm installer
          inputs: 
            helmVersionToInstall: latest

        - task: HelmDeploy@0
          displayName: 'helm init'
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: ${{ parameters.aksConnection }}
            command: init
            upgradetiller: true
            waitForExecution: true
            tillerNamespace: ${{ parameters.namespace }}
            arguments: |
              --service-account tiller
        
        - task: AzureCLI@1
          displayName: 'Connect to ACR Helm Repo'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            scriptLocation: inlineScript
            inlineScript: 'az acr helm repo add -n ${{ parameters.acrName }}'

        - task: HelmDeploy@0
          displayName: Helm deploy
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: ${{ parameters.aksConnection }}
            command: upgrade
            chartType: Name
            chartName: ${{ format('{0}/{1}', parameters.acrName, parameters.chartName) }}
            releaseName: ${{parameters.releaseName}}
            install: true # this doesn't work for first time installs :-( deploy manually first
            waitForExecution: false
            namespace: ${{ parameters.namespace }}
            tillerNamespace: ${{ parameters.namespace }}
            overrideValues: ${{ parameters.helmOverrideValues }} #command seperated list with no spaces