version: '3.4'

services:
  sql.data:
    environment: 
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  keystore.data:
    ports:
      - "6379:6379"

  identity:
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=${IDENTITY_DB:-Server=sql.data;Database=KetoPal.Identity.IdentityDb;User Id=sa;Password=Pass@word}
      - DPConnectionString=keystore.data
    ports:
      - "5000:80"

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44319
    ports:
      - "45339:80"
      - "44319:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  api.data:
    environment: 
      - "SA_PASSWORD=#newPass1"
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44320
    ports:
      - "45340:80"
      - "44320:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro  