version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  identity:
    image: ${REGISTRY:-ketopal}/identity:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: .
      dockerfile: src/Services/Identity/KetoPal.Identity/Dockerfile
    depends_on: 
      - sql.data 

  api:
    image: ${REGISTRY-ketopal}/api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/API/KetoPal.Api/Dockerfile
    depends_on:
      - api.data

  api.data:
    image: fgauna12/fooddb

  gateway:
    image: ${REGISTRY-ketopal}/gateway:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Gateways/KetoPal.Gateway/Dockerfile
    depends_on:
      - api
