version: '3.4'

services:
  sql.data:
    environment: 
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  identity:
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${IDENTITY_DB:-Server=sql.data;Database=KetoPal.Identity.IdentityDb;User Id=sa;Password=Pass@word}
    ports:
      - "5000:80"